#!/usr/bin/env ruby

require "bwa/client"
require "bwa/discovery"

def watch(spa)
  loop do
    message = spa.poll
    next if message.is_a?(BWA::Messages::Ready)

    puts message.raw_data.unpack1("H*").scan(/[0-9a-f]{2}/).join(" ")
    puts message.inspect
    break if block_given? && yield
  rescue BWA::InvalidMessage => e
    puts e.message
    puts e.raw_data.unpack1("H*").scan(/[0-9a-f]{2}/).join(" ")
    break
  end
end

if ARGV.empty?
  spas = BWA::Discovery.discover
  if spas.empty?
    warn "Could not find spa!"
    exit 1
  end
  spa_ip = "tcp://" + spas.first.first + "/"
else
  spa_ip = ARGV[0]
end

spa = BWA::Client.new(spa_ip)

spa.request_configuration
spa.request_control_info
watch(spa) do
  spa.last_status
end

watch(spa)
